# Generated by Django 2.2.1 on 2019-06-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiGnokhor', '0002_client_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('typelunette', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, upload_to='post_image')),
            ],
        ),
    ]
