# Generated by Django 2.2.1 on 2019-06-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiGnokhor', '0003_lunette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nbre_lunettes', models.IntegerField()),
                ('montant_total', models.IntegerField()),
                ('Client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiGnokhor.Client')),
                ('lunette_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiGnokhor.Lunette')),
            ],
        ),
    ]
